### ISSUE TITLE
Maybe make some in mounting?

### ISSUE THREAD

**Issue by radioblahaj** [SheepTester/themes#1]
Mounting.

Anyways cool

**Comment by AmazingMech2418** [comment]
Mounting? @redmangospros

**Comment by radioblahaj** [comment]
Auto-correct,

**Comment by SheepTester** [comment]
What did you mean to say instead of "mounting"?

**Comment by radioblahaj** [comment]
Mountio, But Now Gitcowor. 

I want to your help.

**Comment by SheepTester** [comment]
Closed for inactivity; open a new issue if the problem persists
